// Code generated by Kitex v1.18.3. DO NOT EDIT.

package itemservice

import (
	client "code.byted.org/kite/kitex/client"
	"context"
	"errors"
	rpc "github.com/Yotinx/go_demo/kitex_gen/toutiao/demo/rpc"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetItem": kitex.NewMethodInfo(
		getItemHandler,
		newItemServiceGetItemArgs,
		newItemServiceGetItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	itemServiceServiceInfo                = NewServiceInfo()
	itemServiceServiceInfoForClient       = NewServiceInfoForClient()
	itemServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return itemServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return itemServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return itemServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ItemService"
	handlerType := (*rpc.ItemService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "rpc",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v1.18.3",
		Extra:           extra,
	}
	return svcInfo
}

func getItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.ItemServiceGetItemArgs)
	realResult := result.(*rpc.ItemServiceGetItemResult)
	success, err := handler.(rpc.ItemService).GetItem(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceGetItemArgs() interface{} {
	return rpc.NewItemServiceGetItemArgs()
}

func newItemServiceGetItemResult() interface{} {
	return rpc.NewItemServiceGetItemResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetItem(ctx context.Context, req *rpc.GetItemRequest) (r *rpc.GetItemResponse, err error) {
	var _args rpc.ItemServiceGetItemArgs
	_args.Req = req
	var _result rpc.ItemServiceGetItemResult
	if err = p.c.Call(ctx, "GetItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
